from odoo import models, fields, api, _


class SelectProductsLine(models.TransientModel):
    _name = 'select.products.line'

    name = fields.Char(string="Name")
    carton_packing = fields.Float(string="Carton Packing")
    packing = fields.Char(string="Packing")
    inventory = fields.Integer(string="Warehouse")
    reserve = fields.Char(string="Reserve")
    list = fields.Integer(string="List")
    is_default_eu = fields.Boolean(string="Select EU")
    eu_date = fields.Date(string="EU Date")
    eu_price = fields.Char(string="EU Price", readonly=True)
    eu_disc = fields.Char(string="EU Discount", readonly=True)
    is_default_rt = fields.Boolean(string="Select RT")
    rt_date = fields.Date(string="RT Date")
    rt_price = fields.Char(string="RT Price", readonly=True)
    rt_disc = fields.Char(string="RT Discount", readonly=True)
    rt_comm = fields.Char(string="RT Commission")
    is_default_pv = fields.Boolean(string="Select PV")
    pv_date = fields.Date(string="PV Date")
    pv_price = fields.Char(string="PV Price", readonly=True)
    pv_disc = fields.Char(string="PV Discount", readonly=True)
    pv_comm = fields.Char(string="PV Commission")
    is_default_ws = fields.Boolean(string="Select WS")
    ws_date = fields.Date(string="WS Date")
    ws_price = fields.Char(string="WS Price", readonly=True)
    ws_disc = fields.Char(string="WS Discount", readonly=True)
    ws_comm = fields.Char(string="WS Commission")
    eu_sel_1 = fields.Boolean()
    eu_vol_1 = fields.Char(string="EU Vol 1")
    eu_price_1 = fields.Char(string="EU Price 1", readonly=True)
    eu_disc_1 = fields.Char(string="EU Disc 1", readonly=True)
    eu_sel_2 = fields.Boolean()
    eu_vol_2 = fields.Char(string="EU Vol 2")
    eu_price_2 = fields.Char(string="EU Price 2", readonly=True)
    eu_disc_2 = fields.Char(string="EU Disc 2", readonly=True)
    eu_sel_3 = fields.Boolean()
    eu_vol_3 = fields.Char(string="EU Vol 3")
    eu_price_3 = fields.Char(string="EU Price 3", readonly=True)
    eu_disc_3 = fields.Char(string="EU Disc 3", readonly=True)
    eu_sel_4 = fields.Boolean()
    eu_vol_4 = fields.Char(string="EU Vol 4")
    eu_price_4 = fields.Char(string="EU Price 4", readonly=True)
    eu_disc_4 = fields.Char(string="EU Disc 4", readonly=True)
    eu_sel_5 = fields.Boolean()
    eu_vol_5 = fields.Char(string="EU Vol 5")
    eu_price_5 = fields.Char(string="EU Price 5", readonly=True)
    eu_disc_5 = fields.Char(string="EU Disc 5", readonly=True)
    eu_sel_6 = fields.Boolean()
    eu_vol_6 = fields.Char(string="EU Vol 6")
    eu_price_6 = fields.Char(string="EU Price 6", readonly=True)
    eu_disc_6 = fields.Char(string="EU Disc 6", readonly=True)
    eu_sel_7 = fields.Boolean()
    eu_vol_7 = fields.Char(string="EU Vol 7")
    eu_price_7 = fields.Char(string="EU Price 7")
    eu_disc_7 = fields.Char(string="EU Disc 7")
    eu_sel_8 = fields.Boolean()
    eu_vol_8 = fields.Char(string="EU Vol 8")
    eu_price_8 = fields.Char(string="EU Price 8", readonly=True)
    eu_disc_8 = fields.Char(string="EU Disc 8", readonly=True)
    eu_sel_9 = fields.Boolean()
    eu_vol_9 = fields.Char(string="EU Vol 9")
    eu_price_9 = fields.Char(string="EU Price 9", readonly=True)
    eu_disc_9 = fields.Char(string="EU Disc 9", readonly=True)
    eu_sel_10 = fields.Boolean()
    eu_vol_10 = fields.Char(string="EU Vol 10")
    eu_price_10 = fields.Char(string="EU Price 10", readonly=True)
    eu_disc_10 = fields.Char(string="EU Disc 10", readonly=True)
    rt_sel_1 = fields.Boolean()
    rt_vol_1 = fields.Integer(string="RT Vol 1 qty")
    rt_vol_package_1 = fields.Integer(string="RT Vol 1 (packaging)")
    rt_free_product_1 = fields.Many2one('product.product', string="RT Free 1 Product")
    rt_free_product_qty_1 = fields.Integer(string="RT Free 1 Product qty")
    rt_free_product_pkg_1 = fields.Many2one('product.packaging', string="RT Free 1 Product Package")
    rt_price_1 = fields.Char(string="RT Price 1", readonly=True)
    rt_disc_1 = fields.Char(string="RT Disc 1", readonly=True)
    rt_com_1 = fields.Char(string="RT Com 1")
    rt_sel_2 = fields.Boolean()
    rt_vol_2 = fields.Integer(string="RT Vol 2 qty")
    rt_vol_package_2 = fields.Integer(string="RT Vol 2 (packaging)")
    rt_free_product_2 = fields.Many2one('product.product', string="RT Free 2 Product")
    rt_free_product_qty_2 = fields.Integer(string="RT Free 2 Product qty")
    rt_free_product_pkg_2 = fields.Many2one('product.packaging', string="RT Free 2 Product Package")
    rt_price_2 = fields.Char(string="RT Price 2", readonly=True)
    rt_disc_2 = fields.Char(string="RT Disc 2", readonly=True)
    rt_com_2 = fields.Char(string="RT Com 2")
    rt_sel_3 = fields.Boolean()
    rt_vol_3 = fields.Integer(string="RT Vol 3 qty")
    rt_vol_package_3 = fields.Integer(string="RT Vol 3 (packaging)")
    rt_free_product_3 = fields.Many2one('product.product', string="RT Free 3 Product")
    rt_free_product_qty_3 = fields.Integer(string="RT Free 3 Product qty")
    rt_free_product_pkg_3 = fields.Many2one('product.packaging', string="RT Free 3 Product Package")
    rt_price_3 = fields.Char(string="RT Price 3", readonly=True)
    rt_disc_3 = fields.Char(string="RT Disc 3", readonly=True)
    rt_com_3 = fields.Char(string="RT Com 3")
    rt_sel_4 = fields.Boolean()
    rt_vol_4 = fields.Integer(string="RT Vol 4 qty")
    rt_vol_package_4 = fields.Integer(string="RT Vol 4 (packaging)")
    rt_free_product_4 = fields.Many2one('product.product', string="RT Free 4 Product")
    rt_free_product_qty_4 = fields.Integer(string="RT Free 4 Product qty")
    rt_free_product_pkg_4 = fields.Many2one('product.packaging', string="RT Free 4 Product Package")
    rt_price_4 = fields.Char(string="RT Price 4", readonly=True)
    rt_disc_4 = fields.Char(string="RT Disc 4", readonly=True)
    rt_com_4 = fields.Char(string="RT Com 4")
    rt_sel_5 = fields.Boolean()
    rt_vol_5 = fields.Integer(string="RT Vol 5 qty")
    rt_vol_package_5 = fields.Integer(string="RT Vol 5 (packaging)")
    rt_free_product_5 = fields.Many2one('product.product', string="RT Free 5 Product")
    rt_free_product_qty_5 = fields.Integer(string="RT Free 5 Product qty")
    rt_free_product_pkg_5 = fields.Many2one('product.packaging', string="RT Free 5 Product Package")
    rt_price_5 = fields.Char(string="RT Price 5", readonly=True)
    rt_disc_5 = fields.Char(string="RT Disc 5", readonly=True)
    rt_com_5 = fields.Char(string="RT Com 5")
    rt_sel_6 = fields.Boolean()
    rt_vol_6 = fields.Integer(string="RT Vol 6 qty")
    rt_vol_package_6 = fields.Integer(string="RT Vol 6 (packaging)")
    rt_free_product_6 = fields.Many2one('product.product', string="RT Free 6 Product")
    rt_free_product_qty_6 = fields.Integer(string="RT Free 6 Product qty")
    rt_free_product_pkg_6 = fields.Many2one('product.packaging', string="RT Free 6 Product Package")
    rt_price_6 = fields.Char(string="RT Price 6", readonly=True)
    rt_disc_6 = fields.Char(string="RT Disc 6", readonly=True)
    rt_com_6 = fields.Char(string="RT Com 6")
    rt_sel_7 = fields.Boolean()
    rt_vol_7 = fields.Integer(string="RT Vol 7 qty")
    rt_vol_package_7 = fields.Integer(string="RT Vol 7 (packaging)")
    rt_free_product_7 = fields.Many2one('product.product', string="RT Free 7 Product")
    rt_free_product_qty_7 = fields.Integer(string="RT Free 7 Product qty")
    rt_free_product_pkg_7 = fields.Many2one('product.packaging', string="RT Free 7 Product Package")
    rt_price_7 = fields.Char(string="RT Price 7", readonly=True)
    rt_disc_7 = fields.Char(string="RT Disc 7", readonly=True)
    rt_com_7 = fields.Char(string="RT Com 7")
    rt_sel_8 = fields.Boolean()
    rt_vol_8 = fields.Integer(string="RT Vol 8 qty")
    rt_vol_package_8 = fields.Integer(string="RT Vol 8 (packaging)")
    rt_free_product_8 = fields.Many2one('product.product', string="RT Free 8 Product")
    rt_free_product_qty_8 = fields.Integer(string="RT Free 8 Product qty")
    rt_free_product_pkg_8 = fields.Many2one('product.packaging', string="RT Free 8 Product Package")
    rt_price_8 = fields.Char(string="RT Price 8", readonly=True)
    rt_disc_8 = fields.Char(string="RT Disc 8", readonly=True)
    rt_com_8 = fields.Char(string="RT Com 8")
    rt_sel_9 = fields.Boolean()
    rt_vol_9 = fields.Integer(string="RT Vol 9 qty")
    rt_vol_package_9 = fields.Integer(string="RT Vol 9 (packaging)")
    rt_free_product_9 = fields.Many2one('product.product', string="RT Free 9 Product")
    rt_free_product_qty_9 = fields.Integer(string="RT Free 9 Product qty")
    rt_free_product_pkg_9 = fields.Many2one('product.packaging', string="RT Free 9 Product Package")
    rt_price_9 = fields.Char(string="RT Price 9", readonly=True)
    rt_disc_9 = fields.Char(string="RT Disc 9", readonly=True)
    rt_com_9 = fields.Char(string="RT Com 9")
    rt_sel_10 = fields.Boolean()
    rt_vol_10 = fields.Integer(string="RT Vol 10 qty")
    rt_vol_package_10 = fields.Integer(string="RT Vol 10 (packaging)")
    rt_free_product_10 = fields.Many2one('product.product', string="RT Free 10 Product")
    rt_free_product_qty_10 = fields.Integer(string="RT Free 10 Product qty")
    rt_free_product_pkg_10 = fields.Many2one('product.packaging', string="RT Free 10 Product Package")
    rt_price_10 = fields.Char(string="RT Price 10", readonly=True)
    rt_disc_10 = fields.Char(string="RT Disc 10", readonly=True)
    rt_com_10 = fields.Char(string="RT Com 10")
    pv_sel_1 = fields.Boolean()
    pv_vol_1 = fields.Char(string="PV Vol 1")
    pv_price_1 = fields.Char(string="PV Price 1", readonly=True)
    pv_disc_1 = fields.Char(string="PV Disc 1", readonly=True)
    pv_com_1 = fields.Char(string="PV Com 1")
    pv_sel_2 = fields.Boolean()
    pv_vol_2 = fields.Char(string="PV Vol 2")
    pv_price_2 = fields.Char(string="PV Price 2", readonly=True)
    pv_disc_2 = fields.Char(string="PV Disc 2", readonly=True)
    pv_com_2 = fields.Char(string="PV Com 2")
    pv_sel_3 = fields.Boolean()
    pv_vol_3 = fields.Char(string="PV Vol 3")
    pv_price_3 = fields.Char(string="PV Price 3", readonly=True)
    pv_disc_3 = fields.Char(string="PV Disc 3", readonly=True)
    pv_com_3 = fields.Char(string="PV Com 3")
    pv_sel_4 = fields.Boolean()
    pv_vol_4 = fields.Char(string="PV Vol 4")
    pv_price_4 = fields.Char(string="PV Price 4", readonly=True)
    pv_disc_4 = fields.Char(string="PV Disc 4", readonly=True)
    pv_com_4 = fields.Char(string="PV Com 4")
    pv_sel_5 = fields.Boolean()
    pv_vol_5 = fields.Char(string="PV Vol 5")
    pv_price_5 = fields.Char(string="PV Price 5", readonly=True)
    pv_disc_5 = fields.Char(string="PV Disc 5", readonly=True)
    pv_com_5 = fields.Char(string="PV Com 5")
    pv_sel_6 = fields.Boolean()
    pv_vol_6 = fields.Char(string="PV Vol 6")
    pv_price_6 = fields.Char(string="PV Price 6", readonly=True)
    pv_disc_6 = fields.Char(string="PV Disc 6", readonly=True)
    pv_com_6 = fields.Char(string="PV Com 6")
    pv_sel_7 = fields.Boolean()
    pv_vol_7 = fields.Char(string="PV Vol 7")
    pv_price_7 = fields.Char(string="PV Price 7", readonly=True)
    pv_disc_7 = fields.Char(string="PV Disc 7", readonly=True)
    pv_com_7 = fields.Char(string="PV Com 7")
    pv_sel_8 = fields.Boolean()
    pv_vol_8 = fields.Char(string="PV Vol 8")
    pv_price_8 = fields.Char(string="PV Price 8", readonly=True)
    pv_disc_8 = fields.Char(string="PV Disc 8", readonly=True)
    pv_com_8 = fields.Char(string="PV Com 8")
    pv_sel_9 = fields.Boolean()
    pv_vol_9 = fields.Char(string="PV Vol 9")
    pv_price_9 = fields.Char(string="PV Price 9", readonly=True)
    pv_disc_9 = fields.Char(string="PV Disc 9", readonly=True)
    pv_com_9 = fields.Char(string="PV Com 9")
    pv_sel_10 = fields.Boolean()
    pv_vol_10 = fields.Char(string="PV Vol 10")
    pv_price_10 = fields.Char(string="PV Price 10", readonly=True)
    pv_disc_10 = fields.Char(string="PV Disc 10", readonly=True)
    pv_com_10 = fields.Char(string="PV Com 10")
    ws_sel_1 = fields.Boolean()
    ws_vol_1 = fields.Integer(string="WS Vol 1 qty")
    ws_vol_package_1 = fields.Integer(string="WS Vol 1 (packaging)")
    ws_free_product_1 = fields.Many2one('product.product', string="WS Free 1 Product")
    ws_free_product_qty_1 = fields.Integer(string="WS Free 1 Product qty")
    ws_free_product_pkg_1 = fields.Many2one('product.packaging', string="WS Free 1 Product Package")
    ws_price_1 = fields.Float(string="WS Price 1", readonly=True)
    ws_disc_1 = fields.Float(string="WS Disc 1", readonly=True)
    ws_com_1 = fields.Char(string="WS Com 1")
    ws_sel_2 = fields.Boolean()
    ws_vol_2 = fields.Integer(string="WS Vol 1 qty")
    ws_vol_package_2 = fields.Integer(string="WS Vol 2 (packaging)")
    ws_free_product_2 = fields.Many2one('product.product', string="WS Free 2 Product")
    ws_free_product_qty_2 = fields.Integer(string="WS Free 2 Product qty")
    ws_free_product_pkg_2 = fields.Many2one('product.packaging', string="WS Free 2 Product Package")
    ws_price_2 = fields.Float(string="WS Price 2", readonly=True)
    ws_disc_2 = fields.Float(string="WS Disc 2", readonly=True)
    ws_com_2 = fields.Char(string="WS Com 2")
    ws_sel_3 = fields.Boolean()
    ws_vol_3 = fields.Integer(string="WS Vol 1 qty")
    ws_vol_package_3 = fields.Integer(string="WS Vol 3 (packaging)")
    ws_free_product_3 = fields.Many2one('product.product', string="WS Free 3 Product")
    ws_free_product_qty_3 = fields.Integer(string="WS Free 3 Product qty")
    ws_free_product_pkg_3 = fields.Many2one('product.packaging', string="WS Free 3 Product Package")
    ws_price_3 = fields.Float(string="WS Price 3", readonly=True)
    ws_disc_3 = fields.Float(string="WS Disc 3", readonly=True)
    ws_com_3 = fields.Char(string="WS Com 3")
    ws_sel_4 = fields.Boolean()
    ws_vol_4 = fields.Integer(string="WS Vol 4 qty")
    ws_vol_package_4 = fields.Integer(string="WS Vol 4 (packaging)")
    ws_free_product_4 = fields.Many2one('product.product', string="WS Free 4 Product")
    ws_free_product_qty_4 = fields.Integer(string="WS Free 4 Product qty")
    ws_free_product_pkg_4 = fields.Many2one('product.packaging', string="WS Free 4 Product Package")
    ws_price_4 = fields.Float(string="WS Price 4", readonly=True)
    ws_disc_4 = fields.Float(string="WS Disc 4", readonly=True)
    ws_com_4 = fields.Char(string="WS Com 4")
    ws_sel_5 = fields.Boolean()
    ws_vol_5 = fields.Integer(string="WS Vol 5 qty")
    ws_vol_package_5 = fields.Integer(string="WS Vol 5 (packaging)")
    ws_free_product_5 = fields.Many2one('product.product', string="WS Free 5 Product")
    ws_free_product_qty_5 = fields.Integer(string="WS Free 5 Product qty")
    ws_free_product_pkg_5 = fields.Many2one('product.packaging', string="WS Free 5 Product Package")
    ws_price_5 = fields.Float(string="WS Price 5", readonly=True)
    ws_disc_5 = fields.Float(string="WS Disc 5", readonly=True)
    ws_com_5 = fields.Char(string="WS Com 5")
    ws_sel_6 = fields.Boolean()
    ws_vol_6 = fields.Integer(string="WS Vol 6 qty")
    ws_vol_package_6 = fields.Integer(string="WS Vol 6 (packaging)")
    ws_free_product_6 = fields.Many2one('product.product', string="WS Free 6 Product")
    ws_free_product_qty_6 = fields.Integer( string="WS Free 6 Product qty")
    ws_free_product_pkg_6 = fields.Many2one('product.packaging', string="WS Free 6 Product Package")
    ws_price_6 = fields.Float(string="WS Price 6", readonly=True)
    ws_disc_6 = fields.Float(string="WS Disc 6", readonly=True)
    ws_com_6 = fields.Char(string="WS Com 6")
    ws_sel_7 = fields.Boolean()
    ws_vol_7 = fields.Integer(string="WS Vol 7 qty")
    ws_vol_package_7 = fields.Integer(string="WS Vol 7 (packaging)")
    ws_free_product_7 = fields.Many2one('product.product', string="WS Free 7 Product")
    ws_free_product_qty_7 = fields.Integer(string="WS Free 7 Product qty")
    ws_free_product_pkg_7 = fields.Many2one('product.packaging', string="WS Free 7 Product Package")
    ws_price_7 = fields.Float(string="WS Price 7", readonly=True)
    ws_disc_7 = fields.Float(string="WS Disc 7", readonly=True)
    ws_com_7 = fields.Char(string="WS Com 7")
    ws_sel_8 = fields.Boolean()
    ws_vol_8 = fields.Integer(string="WS Vol 8 qty")
    ws_vol_package_8 = fields.Integer(string="WS Vol 8 (packaging)")
    ws_free_product_8 = fields.Many2one('product.product', string="WS Free 8 Product")
    ws_free_product_qty_8 = fields.Integer(string="WS Free 8 Product qty")
    ws_free_product_pkg_8 = fields.Many2one('product.packaging', string="WS Free 8 Product Package")
    ws_price_8 = fields.Float(string="WS Price 8", readonly=True)
    ws_disc_8 = fields.Float(string="WS Disc 8", readonly=True)
    ws_com_8 = fields.Char(string="WS Com 8")
    ws_sel_9 = fields.Boolean()
    ws_vol_9 = fields.Integer(string="WS Vol 9 qty")
    ws_vol_package_9 = fields.Integer(string="WS Vol 9 (packaging)")
    ws_free_product_9 = fields.Many2one('product.product', string="WS Free 9 Product")
    ws_free_product_qty_9 = fields.Integer(string="WS Free 9 Product qty")
    ws_free_product_pkg_9 = fields.Many2one('product.packaging', string="WS Free 9 Product Package")
    ws_price_9 = fields.Float(string="WS Price 9", readonly=True)
    ws_disc_9 = fields.Float(string="WS Disc 9", readonly=True)
    ws_com_9 = fields.Char(string="WS Com 9")
    ws_sel_10 = fields.Boolean()
    ws_vol_10 = fields.Integer(string="WS Vol 10 qty")
    ws_vol_package_10 = fields.Integer(string="WS Vol 10 (packaging)")
    ws_free_product_10 = fields.Many2one('product.product', string="WS Free 10 Product")
    ws_free_product_qty_10 = fields.Integer(string="WS Free 10 Product qty")
    ws_free_product_pkg_10 = fields.Many2one('product.packaging', string="WS Free 10 Product Package")
    ws_price_10 = fields.Float(string="WS Price 10", readonly=True)
    ws_disc_10 = fields.Float(string="WS Disc 10", readonly=True)
    ws_com_10 = fields.Char(string="WS Com 10")
    select_id = fields.Many2one('select.products')
    display_all_types = fields.Boolean(string='Display all types', related="select_id.display_all_types", store=True)
    ws_count = fields.Integer(string='WS Count', related="select_id.ws_count")
    rt_count = fields.Integer(string='RT Count', related="select_id.rt_count")
    eu_count = fields.Integer(string='EU Count', related="select_id.eu_count")
    pv_count = fields.Integer(string='PV Count', related="select_id.pv_count")    
    is_selsected = fields.Boolean(store=True, string="Select Product")
    product_id = fields.Many2one('product.product')
    line_check = fields.Boolean()

    @api.onchange('is_selsected')
    def _onchange_is_selsected(self):
        if self.is_selsected:
            if self.select_id.customer_type == 'RT':
                self.is_default_rt = True
            if self.select_id.customer_type == 'EU':
                self.is_default_eu = True
            if self.select_id.customer_type == 'WS':
                self.is_default_ws = True
            if self.select_id.customer_type == 'PV':
                self.is_default_pv = True