from odoo import api, fields, models


class ProductPriceVariencepv(models.Model):
    _name = 'product.pvpricevarience'

    product_pvpriceid = fields.Many2one('product.template')
    price = fields.Char(string="PV Price")
    discount = fields.Char(string="PV Discount")
    commission = fields.Char(string="PV Commision")
    date = fields.Datetime(string="PV Date")
    pv_vol_1 = fields.Char(string="PV Vol 1")
    pv_price_1 = fields.Char(string="PV Price 1")
    pv_disc_1 = fields.Char(string="PV Disc 1")
    pv_com_1 = fields.Char(string="PV Com 1")
    pv_vol_2 = fields.Char(string="PV Vol 2")
    pv_price_2 = fields.Char(string="PV Price 2")
    pv_disc_2 = fields.Char(string="PV Disc 2")
    pv_com_2 = fields.Char(string="PV Com 2")
    pv_vol_3 = fields.Char(string="PV Vol 3")
    pv_price_3 = fields.Char(string="PV Price 3")
    pv_disc_3 = fields.Char(string="PV Disc 3")
    pv_com_3 = fields.Char(string="PV Com 3")
    pv_vol_4 = fields.Char(string="PV Vol 4")
    pv_price_4 = fields.Char(string="PV Price 4")
    pv_disc_4 = fields.Char(string="PV Disc 4")
    pv_com_4 = fields.Char(string="PV Com 4")
    pv_vol_5 = fields.Char(string="PV Vol 5")
    pv_price_5 = fields.Char(string="PV Price 5")
    pv_disc_5 = fields.Char(string="PV Disc 5")
    pv_com_5 = fields.Char(string="PV Com 5")
    pv_vol_6 = fields.Char(string="PV Vol 6")
    pv_price_6 = fields.Char(string="PV Price 6")
    pv_disc_6 = fields.Char(string="PV Disc 6")
    pv_com_6 = fields.Char(string="PV Com 6")
    pv_vol_7 = fields.Char(string="PV Vol 7")
    pv_price_7 = fields.Char(string="PV Price 7")
    pv_disc_7 = fields.Char(string="PV Disc 7")
    pv_com_7 = fields.Char(string="PV Com 7")
    pv_vol_8 = fields.Char(string="PV Vol 8")
    pv_price_8 = fields.Char(string="PV Price 8")
    pv_disc_8 = fields.Char(string="PV Disc 8")
    pv_com_8 = fields.Char(string="PV Com 8")
    pv_vol_9 = fields.Char(string="PV Vol 9")
    pv_price_9 = fields.Char(string="PV Price 9")
    pv_disc_9 = fields.Char(string="PV Disc 9")
    pv_com_9 = fields.Char(string="PV Com 9")
    pv_vol_10 = fields.Char(string="PV Vol 10")
    pv_price_10 = fields.Char(string="PV Price 10")
    pv_disc_10 = fields.Char(string="PV Disc 10")
    pv_com_10 = fields.Char(string="PV Com 10")



