from odoo import api, fields, models

class ProductPriceVariencert(models.Model):
    _name = 'product.rtpricevarience'

    product_rtpriceid = fields.Many2one('product.template')
    price = fields.Char(string="RT Price")
    discount = fields.Char(string="RT Discount")
    commission = fields.Char(string="RT Commision")
    date = fields.Datetime(string="RT Date")
    rt_price_1 = fields.Char(string="RT Price 1")
    rt_disc_1 = fields.Char(string="RT Disc 1")
    rt_com_1 = fields.Char(string="RT Com 1")
    rt_price_2 = fields.Char(string="RT Price 2")
    rt_disc_2 = fields.Char(string="RT Disc 2")
    rt_com_2 = fields.Char(string="RT Com 2")
    rt_price_3 = fields.Char(string="RT Price 3")
    rt_disc_3 = fields.Char(string="RT Disc 3")
    rt_com_3 = fields.Char(string="RT Com 3")
    rt_price_4 = fields.Char(string="RT Price 4")
    rt_disc_4 = fields.Char(string="RT Disc 4")
    rt_com_4 = fields.Char(string="RT Com 4")
    rt_price_5 = fields.Char(string="RT Price 5")
    rt_disc_5 = fields.Char(string="RT Disc 5")
    rt_com_5 = fields.Char(string="RT Com 5")
    rt_price_6 = fields.Char(string="RT Price 6")
    rt_disc_6 = fields.Char(string="RT Disc 6")
    rt_com_6 = fields.Char(string="RT Com 6")
    rt_price_7 = fields.Char(string="RT Price 7")
    rt_disc_7 = fields.Char(string="RT Disc 7")
    rt_com_7 = fields.Char(string="RT Com 7")
    rt_price_8 = fields.Char(string="RT Price 8")
    rt_disc_8 = fields.Char(string="RT Disc 8")
    rt_com_8 = fields.Char(string="RT Com 8")
    rt_price_9 = fields.Char(string="RT Price 9")
    rt_disc_9 = fields.Char(string="RT Disc 9")
    rt_com_9 = fields.Char(string="RT Com 9")
    rt_price_10 = fields.Char(string="RT Price 10")
    rt_disc_10 = fields.Char(string="RT Disc 10")
    rt_com_10 = fields.Char(string="RT Com 10")
    rt_vol_1 = fields.Integer(string="RT Vol 1 qty")
    rt_vol_package_1 = fields.Integer(string="RT Vol 1 (packaging)")
    rt_free_product_1 = fields.Many2one('product.product', string="RT Free 1 Product")
    rt_free_product_qty_1 = fields.Integer(string="RT Free 1 Product qty")
    rt_free_product_pkg_1 = fields.Many2one('product.packaging', string="RT Free 1 Product Package")
    rt_vol_2 = fields.Integer(string="RT Vol 2 qty")
    rt_vol_package_2 = fields.Integer(string="RT Vol 2 (packaging)")
    rt_free_product_2 = fields.Many2one('product.product', string="RT Free 2 Product")
    rt_free_product_qty_2 = fields.Integer(string="RT Free 2 Product qty")
    rt_free_product_pkg_2 = fields.Many2one('product.packaging', string="RT Free 2 Product Package")
    rt_vol_3 = fields.Integer(string="RT Vol 3 qty")
    rt_vol_package_3 = fields.Integer(string="RT Vol 3 (packaging)")
    rt_free_product_3 = fields.Many2one('product.product', string="RT Free 3 Product")
    rt_free_product_qty_3 = fields.Integer(string="RT Free 3 Product qty")
    rt_free_product_pkg_3 = fields.Many2one('product.packaging', string="RT Free 3 Product Package")
    rt_vol_4 = fields.Integer(string="RT Vol 4 qty")
    rt_vol_package_4 = fields.Integer(string="RT Vol 4 (packaging)")
    rt_free_product_4 = fields.Many2one('product.product', string="RT Free 4 Product")
    rt_free_product_qty_4 = fields.Integer(string="RT Free 4 Product qty")
    rt_free_product_pkg_4 = fields.Many2one('product.packaging', string="RT Free 4 Product Package")
    rt_vol_5 = fields.Integer(string="RT Vol 5 qty")
    rt_vol_package_5 = fields.Integer(string="RT Vol 5 (packaging)")
    rt_free_product_5 = fields.Many2one('product.product', string="RT Free 5 Product")
    rt_free_product_qty_5 = fields.Integer(string="RT Free 5 Product qty")
    rt_free_product_pkg_5 = fields.Many2one('product.packaging', string="RT Free 5 Product Package")
    rt_vol_6 = fields.Integer(string="RT Vol 6 qty")
    rt_vol_package_6 = fields.Integer(string="RT Vol 6 (packaging)")
    rt_free_product_6 = fields.Many2one('product.product', string="RT Free 6 Product")
    rt_free_product_qty_6 = fields.Integer(string="RT Free 6 Product qty")
    rt_free_product_pkg_6 = fields.Many2one('product.packaging', string="RT Free 6 Product Package")
    rt_vol_7 = fields.Integer(string="RT Vol 7 qty")
    rt_vol_package_7 = fields.Integer(string="RT Vol 7 (packaging)")
    rt_free_product_7 = fields.Many2one('product.product', string="RT Free 7 Product")
    rt_free_product_qty_7 = fields.Integer(string="RT Free 7 Product qty")
    rt_free_product_pkg_7 = fields.Many2one('product.packaging', string="RT Free 7 Product Package")
    rt_vol_8 = fields.Integer(string="RT Vol 8 qty")
    rt_vol_package_8 = fields.Integer(string="RT Vol 8 (packaging)")
    rt_free_product_8 = fields.Many2one('product.product', string="RT Free 8 Product")
    rt_free_product_qty_8 = fields.Integer(string="RT Free 8 Product qty")
    rt_free_product_pkg_8 = fields.Many2one('product.packaging', string="RT Free 8 Product Package")
    rt_vol_9 = fields.Integer(string="RT Vol 9 qty")
    rt_vol_package_9 = fields.Integer(string="RT Vol 9 (packaging)")
    rt_free_product_9 = fields.Many2one('product.product', string="RT Free 9 Product")
    rt_free_product_qty_9 = fields.Integer(string="RT Free 9 Product qty")
    rt_free_product_pkg_9 = fields.Many2one('product.packaging', string="RT Free 9 Product Package")
    rt_vol_10 = fields.Integer(string="RT Vol 10 qty")
    rt_vol_package_10 = fields.Integer(string="RT Vol 10 (packaging)")
    rt_free_product_10 = fields.Many2one('product.product', string="RT Free 10 Product")
    rt_free_product_qty_10 = fields.Integer(string="RT Free 10 Product qty")
    rt_free_product_pkg_10 = fields.Many2one('product.packaging', string="RT Free 10 Product Package")