from odoo import api, fields, models

class ProductPriceVariencews(models.Model):
    _name = 'product.wspricevarience'

    product_wspriceid = fields.Many2one('product.template')
    price = fields.Char(string="WS Price")
    discount = fields.Char(string="WS Discount")
    commission = fields.Char(string="WS Commision")
    date = fields.Datetime(string="WS Date")
    ws_price_1 = fields.Float(string="WS Price 1")
    ws_disc_1 = fields.Float(string="WS Disc 1")
    ws_com_1 = fields.Char(string="WS Com 1")
    ws_price_2 = fields.Float(string="WS Price 2")
    ws_disc_2 = fields.Float(string="WS Disc 2")
    ws_com_2 = fields.Char(string="WS Com 2")
    ws_price_3 = fields.Float(string="WS Price 3")
    ws_disc_3 = fields.Float(string="WS Disc 3")
    ws_com_3 = fields.Char(string="WS Com 3")
    ws_price_4 = fields.Float(string="WS Price 4")
    ws_disc_4 = fields.Float(string="WS Disc 4")
    ws_com_4 = fields.Char(string="WS Com 4")
    ws_price_5 = fields.Float(string="WS Price 5")
    ws_disc_5 = fields.Float(string="WS Disc 5")
    ws_com_5 = fields.Char(string="WS Com 5")
    ws_price_6 = fields.Float(string="WS Price 6")
    ws_disc_6 = fields.Float(string="WS Disc 6")
    ws_com_6 = fields.Char(string="WS Com 6")
    ws_price_7 = fields.Float(string="WS Price 7")
    ws_disc_7 = fields.Float(string="WS Disc 7")
    ws_com_7 = fields.Char(string="WS Com 7")
    ws_price_8 = fields.Float(string="WS Price 8")
    ws_disc_8 = fields.Float(string="WS Disc 8")
    ws_com_8 = fields.Char(string="WS Com 8")
    ws_price_9 = fields.Float(string="WS Price 9")
    ws_disc_9 = fields.Float(string="WS Disc 9")
    ws_com_9 = fields.Char(string="WS Com 9")
    ws_price_10 = fields.Float(string="WS Price 10")
    ws_disc_10 = fields.Float(string="WS Disc 10")
    ws_vol_1 = fields.Integer(string="WS Vol 1 qty")
    ws_vol_package_1 = fields.Integer(string="WS Vol 1 (packaging)")
    ws_free_product_1 = fields.Many2one('product.product', string="WS Free 1 Product")
    ws_free_product_qty_1 = fields.Integer(string="WS Free 1 Product qty")
    ws_free_product_pkg_1 = fields.Many2one('product.packaging', string="WS Free 1 Product Package")
    ws_vol_2 = fields.Integer(string="WS Vol 1 qty")
    ws_vol_package_2 = fields.Integer(string="WS Vol 2 (packaging)")
    ws_free_product_2 = fields.Many2one('product.product', string="WS Free 2 Product")
    ws_free_product_qty_2 = fields.Integer(string="WS Free 2 Product qty")
    ws_free_product_pkg_2 = fields.Many2one('product.packaging', string="WS Free 2 Product Package")
    ws_vol_3 = fields.Integer(string="WS Vol 1 qty")
    ws_vol_package_3 = fields.Integer(string="WS Vol 3 (packaging)")
    ws_free_product_3 = fields.Many2one('product.product', string="WS Free 3 Product")
    ws_free_product_qty_3 = fields.Integer(string="WS Free 3 Product qty")
    ws_free_product_pkg_3 = fields.Many2one('product.packaging', string="WS Free 3 Product Package")
    ws_vol_4 = fields.Integer(string="WS Vol 4 qty")
    ws_vol_package_4 = fields.Integer(string="WS Vol 4 (packaging)")
    ws_free_product_4 = fields.Many2one('product.product', string="WS Free 4 Product")
    ws_free_product_qty_4 = fields.Integer(string="WS Free 4 Product qty")
    ws_free_product_pkg_4 = fields.Many2one('product.packaging', string="WS Free 4 Product Package")
    ws_vol_5 = fields.Integer(string="WS Vol 5 qty")
    ws_vol_package_5 = fields.Integer(string="WS Vol 5 (packaging)")
    ws_free_product_5 = fields.Many2one('product.product', string="WS Free 5 Product")
    ws_free_product_qty_5 = fields.Integer( string="WS Free 5 Product qty")
    ws_free_product_pkg_5 = fields.Many2one('product.packaging', string="WS Free 5 Product Package")
    ws_vol_6 = fields.Integer(string="WS Vol 6 qty")
    ws_vol_package_6 = fields.Integer(string="WS Vol 6 (packaging)")
    ws_free_product_6 = fields.Many2one('product.product', string="WS Free 6 Product")
    ws_free_product_qty_6 = fields.Integer(string="WS Free 6 Product qty")
    ws_free_product_pkg_6 = fields.Many2one('product.packaging', string="WS Free 6 Product Package")
    ws_vol_7 = fields.Integer(string="WS Vol 7 qty")
    ws_vol_package_7 = fields.Integer(string="WS Vol 7 (packaging)")
    ws_free_product_7 = fields.Many2one('product.product', string="WS Free 7 Product")
    ws_free_product_qty_7 = fields.Integer(string="WS Free 7 Product qty")
    ws_free_product_pkg_7 = fields.Many2one('product.packaging', string="WS Free 7 Product Package")
    ws_vol_8 = fields.Integer(string="WS Vol 8 qty")
    ws_vol_package_8 = fields.Integer(string="WS Vol 8 (packaging)")
    ws_free_product_8 = fields.Many2one('product.product', string="WS Free 8 Product")
    ws_free_product_qty_8 = fields.Integer(string="WS Free 8 Product qty")
    ws_free_product_pkg_8 = fields.Many2one('product.packaging', string="WS Free 8 Product Package")
    ws_vol_9 = fields.Integer(string="WS Vol 9 qty")
    ws_vol_package_9 = fields.Integer(string="WS Vol 9 (packaging)")
    ws_free_product_9 = fields.Many2one('product.product', string="WS Free 9 Product")
    ws_free_product_qty_9 = fields.Integer(string="WS Free 9 Product qty")
    ws_free_product_pkg_9 = fields.Many2one('product.packaging', string="WS Free 9 Product Package")
    ws_vol_10 = fields.Integer(string="WS Vol 10 qty")
    ws_vol_package_10 = fields.Integer(string="WS Vol 10 (packaging)")
    ws_free_product_10 = fields.Many2one('product.product', string="WS Free 10 Product")
    ws_free_product_qty_10 = fields.Integer(string="WS Free 10 Product qty")
    ws_free_product_pkg_10 = fields.Many2one('product.packaging', string="WS Free 10 Product Package")
    ws_com_10 = fields.Char(string="WS Com 10")