from odoo import api, fields, models

class ProductPriceVarienceeu(models.Model):
    _name = 'product.eupricevarience'

    product_eupriceid = fields.Many2one('product.template')
    price = fields.Char(string="EU Price")
    discount = fields.Char(string="EU Discount")
    date = fields.Datetime(string="EU Date")
    eu_vol_1 = fields.Char(string="EU Vol 1")
    eu_price_1 = fields.Char(string="EU Price 1")
    eu_disc_1 = fields.Char(string="EU Disc 1")
    eu_vol_2 = fields.Char(string="EU Vol 2")
    eu_price_2 = fields.Char(string="EU Price 2")
    eu_disc_2 = fields.Char(string="EU Disc 2")
    eu_vol_3 = fields.Char(string="EU Vol 3")
    eu_price_3 = fields.Char(string="EU Price 3")
    eu_disc_3 = fields.Char(string="EU Disc 3")
    eu_vol_4 = fields.Char(string="EU Vol 4")
    eu_price_4 = fields.Char(string="EU Price 4")
    eu_disc_4 = fields.Char(string="EU Disc 4")
    eu_vol_5 = fields.Char(string="EU Vol 5")
    eu_price_5 = fields.Char(string="EU Price 5")
    eu_disc_5 = fields.Char(string="EU Disc 5")
    eu_vol_6 = fields.Char(string="EU Vol 6")
    eu_price_6 = fields.Char(string="EU Price 6")
    eu_disc_6 = fields.Char(string="EU Disc 6")
    eu_vol_7 = fields.Char(string="EU Vol 7")
    eu_price_7 = fields.Char(string="EU Price 7")
    eu_disc_7 = fields.Char(string="EU Disc 7")
    eu_vol_8 = fields.Char(string="EU Vol 8")
    eu_price_8 = fields.Char(string="EU Price 8")
    eu_disc_8 = fields.Char(string="EU Disc 8")
    eu_vol_9 = fields.Char(string="EU Vol 9")
    eu_price_9 = fields.Char(string="EU Price 9")
    eu_disc_9 = fields.Char(string="EU Disc 9")
    eu_vol_10 = fields.Char(string="EU Vol 10")
    eu_price_10 = fields.Char(string="EU Price 10")
    eu_disc_10 = fields.Char(string="EU Disc 10")
